#!/bin/bash

check() {
    cmd="$1"

    if eval "$cmd"; then
        echo "👍"
    else
        echo -e "❗"
        exit 1
    fi
}

check_build() {
    echo -n "🔍 Building..."
    check "make build"
}

check_test() {
    echo -n "🔍 Testing..."
    check "make test"
}

set -euo pipefail

check_build
check_test
