name: app

options:
  bundleIdPrefix: example.com
  deploymentTarget:
    iOS: 15.0

targetTemplates:
  EmbeddedFramework:
    platform: iOS
    type: framework
    sources:
      - path: ${target_name}
  EmbeddedFrameworkTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: app
    sources:
      - path: ${target_name}
      - path: ${target_name}
        excludes:
          - Info.plist
        buildPhase: resources
  FeatureFramework:
    platform: iOS
    type: framework
    sources:
      - path: Features/${target_name}/${target_name}
    dependencies:
      - target: Core
  SandboxApp:
    type: application
    platform: iOS
    dependencies:
      - target: Core

targets:
  app:
    type: application
    platform: iOS
    sources:
      - app
    dependencies:
      - target: Core
      - target: Alpha
      - target: Bravo
    preBuildScripts:
      - name: Generate resolving dependencies code
        script: |
          cd "$PROJECT_DIR" && \
          lib/needle/Generator/bin/needle generate \
          app/DI/NeedleGenerated.swift \
          .needle/source_list_files.txt \
          --header-doc .needle/copyright_header.txt

  Core:
    templates:
      - EmbeddedFramework
    transitivelyLinkDependencies: true
    dependencies:
      - target: Umbrella
  Umbrella:
    platform: iOS
    type: framework.static
    dependencies:
      - package: NeedleFoundation
        product: NeedleFoundation

include:
  - Features/Alpha/project.yml
  - Features/Bravo/project.yml

packages:
  NeedleFoundation:
    url: https://github.com/uber/needle
    from: 0.17.2
