name: app

options:
  bundleIdPrefix: example.com
  deploymentTarget:
    iOS: 15.0

targetTemplates:
  EmbeddedFramework:
    platform: iOS
    type: framework
    sources:
      - path: ${target_name}
  EmbeddedFrameworkTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: app
    sources:
      - path: ${target_name}
      - path: ${target_name}
        excludes:
          - Info.plist
        buildPhase: resources
  FeatureFramework:
    platform: iOS
    type: framework
    sources:
      - path: Features/${target_name}/${target_name}
    dependencies:
      - target: Core
  SandboxApp:
    type: application
    platform: iOS
    dependencies:
      - target: Core

targets:
  app:
    type: application
    platform: iOS
    sources:
      - app
    dependencies:
      - target: Core
      - target: Alpha
      - target: Bravo

  Core:
    templates:
      - EmbeddedFramework
    transitivelyLinkDependencies: true
    dependencies:
      - target: Umbrella
  Umbrella:
    platform: iOS
    type: framework.static
    dependencies:
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies

schemeTemplates:
  FeatureScheme:
    build:
      targets:
        ${scheme_name}: all
        ${scheme_name}Tests: [test]
    test:
      targets:
        - ${scheme_name}Tests
      gatherCoverageData: true

schemes:
  app:
    build:
      targets:
        app: all
  Core:
    build:
      targets:
        Core: all

include:
  - Features/Alpha/project.yml
  - Features/Bravo/project.yml

packages:
  swift-composable-architecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.34.0
  swift-dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: 0.1.4
