targets:
  Bravo:
    templates:
      - FeatureFramework
  BravoSandboxApp:
    templates:
      - SandboxApp
    sources:
      - path: ${target_name}
    dependencies:
      - target: Bravo
    preBuildScripts:
      - name: Generate resolving dependencies code
        script: |
          cd "$PROJECT_DIR" && \
          lib/needle/Generator/bin/needle generate \
          Features/Bravo/BravoSandboxApp/NeedleGenerated.swift \
          Features/Bravo \
          --header-doc .needle/copyright_header.txt
