targets:
  Alpha:
    templates:
      - FeatureFramework
  AlphaSandboxApp:
    templates:
      - SandboxApp
    sources:
      - path: ${target_name}
    dependencies:
      - target: Alpha
    preBuildScripts:
      - name: Generate resolving dependencies code
        script: |
          cd "$PROJECT_DIR" && \
          lib/needle/Generator/bin/needle generate \
          Features/Alpha/AlphaSandboxApp/NeedleGenerated.swift \
          Features/Alpha \
          --header-doc .needle/copyright_header.txt
