targets:
  Alpha:
    templates:
      - FeatureFramework
  AlphaTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: AlphaTests
    dependencies:
      - target: Core
      - target: Alpha
    preBuildScripts:
      - name: Generate mock code
        script: |
          cd "$PROJECT_DIR"
          if [ -f ".envrc" ]; then
            source ".envrc"
          fi
          scripts/gen_mock.sh Alpha
  AlphaSandboxApp:
    templates:
      - SandboxApp
    sources:
      - path: ${target_name}
    dependencies:
      - target: Alpha

schemes:
  Alpha:
    templates:
      - FeatureScheme
